artifact_uri: file:D:\Documents\universidad\posgrado\producto de datos\talleres\PRE-08-mlflow-tracking-local-amserranoh\my_mlruns/930836585572126998/d9e5b98fab3749a2aac51a1735f52e62/artifacts
end_time: 1749187764970
entry_point_name: ''
experiment_id: '930836585572126998'
lifecycle_stage: active
run_id: d9e5b98fab3749a2aac51a1735f52e62
run_name: elasticnet_583ab6f4
run_uuid: d9e5b98fab3749a2aac51a1735f52e62
source_name: ''
source_type: 4
source_version: ''
start_time: 1749187764748
status: 3
tags: []
user_id: Ana Serrano
