artifact_uri: file:D:\Documents\universidad\posgrado\producto de datos\talleres\PRE-08-mlflow-tracking-local-amserranoh\my_mlruns/930836585572126998/7fb1030ddd3d410f8f5b5b2581af8a54/artifacts
end_time: 1749189643089
entry_point_name: ''
experiment_id: '930836585572126998'
lifecycle_stage: active
run_id: 7fb1030ddd3d410f8f5b5b2581af8a54
run_name: elasticnet_3cb102be
run_uuid: 7fb1030ddd3d410f8f5b5b2581af8a54
source_name: ''
source_type: 4
source_version: ''
start_time: 1749189642904
status: 3
tags: []
user_id: Ana Serrano
